/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_addressModel'], function() {
    App.Model.AddressModel = App.Model._AddressModel.extend({

 	validate: function(attrs,options){
            var validationMessage = "";
            if(!attrs.street){
                validationMessage = "The street can't be empty";
            }
            else if(!attrs.aveneu){
                validationMessage = "The aveneu can't be empty";
            }
            else if(!attrs.cityId){
                validationMessage = "The city Id can't be empty";
            }
            else if(isNaN(attrs.street)){
                validationMessage = "The street must be a number";
            }
            else if(isNaN(attrs.aveneu)){
                validationMessage = "The avenue must be a number";
            }
            else if(attrs.street.length>3){
                validationMessage = "The street can be at least 3 digit lenght";
            }
            else if(attrs.aveneu.length>3){
                validationMessage = "The aveneu can be at least 3 digit lenght";
            }
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.AddressList = App.Model._AddressList.extend({
        model: App.Model.AddressModel
    });

    return  App.Model.AddressModel;

});