/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_memberModel'], function() {
    App.Model.MemberModel = App.Model._MemberModel.extend({

 	validate: function(attrs,options){
            var validationMessage = "";
            var d = attrs.birthDate.split("/");
            var n = new Date();
            if(!attrs.name){
                validationMessage = "The Name can't be empty.";
            }
            else if(!attrs.firstName){
                validationMessage = "The First Name can't be empty";
            }
            else if(!attrs.lastName){
                validationMessage = "The Last Name can't be empty";
            }
            else if(!attrs.birthDate){
                validationMessage = "The Birth Date can't be empty";
            }
            else if(!attrs.docNumber){
                validationMessage = "The Doc Number can't be empty";
            }
            else if(!attrs.documenttypeId){
                validationMessage = "The Document Type ID can't be empty";
            }
            else if(!attrs.partnerId){
                validationMessage = "The Partner ID can't be empty";
            }
            else if(attrs.docNumber.lenght<5){
                validationMessage = "The Doc Number must be at least 5 characters long";
            }
            else if(d[0]>=n.getDate() && d[1]>=n.getMonth() && d[2]>=n.getFullYear()){
                validationMessage = "The date can't be today or in the future";
            }
            else if(n.getFullYear()-d[2]>100){
                validationMessage = "The member can't be 100 years old";
            }
            else if(n.getFullYear()-d[2]===100){
                if(n.getMonth()>d[1]){
                    validationMessage = "The member can't be 100 years old";
                }
                else if(n.getMonth()===d[1]){
                    if(n.getDate()>=d[0]){
                        validationMessage = "The member can't be 100 years old";
                    }
                }
            }
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.MemberList = App.Model._MemberList.extend({
        model: App.Model.MemberModel
    });

    return  App.Model.MemberModel;

});